[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dirtytorch"
version = "1.0.0"
dependencies = [
    "numpy",
    "opencv-python",
	"Pillow"
]

[tool.setuptools]
packages = [
	"dirtytorch",
	"dirtytorch.scripts"
]

[project.scripts]
dirty="dirtytorch.__main__:main"
enter-dev="dirtytorch.scripts.enterdev:main"
